### PR TITLE
Created snap for pyphoon`

### PR DESCRIPTION
**Pull request by kz6fittycent**
Firstly, thanks for this awesome application! 

I've created a snap for `pyphoon` to make it easier to distribute to all Linux distros without the need to worry about libraries or other dependencies. If you're not sure what snaps are, you can see this [link](https://snapcraft.io/about). 

If you'd prefer to keep control of all distribution of this application, we can take care of that via a post to transfer ownership of the snap to you in [forum.snapcraft.io](forum.snapcraft.io). 

I can continue to support the snap if you'd prefer but typically, it's best that the developer(s) do so. 

Let me know if you're interested and I'd be happy to help.

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much for the help!
Yes, I would like to take control of the application.
Can you please help me?
What are the next steps?

**Comment by kz6fittycent** [comment]
Go to the [Snapcraft Forum](https://forum.snapcraft.io/) and create an account. let me know what your handle/username is and I'll create a new thread, tag you, and request that ownership be transitioned to you. Once done, Canonical will move things over, let us both know in the thread and every time you make a commit to your repo, the build service will build out new versions for publication.

**Comment by kz6fittycent** [comment]
Just checking in. Have you created your account yet?

**Comment by kz6fittycent** [comment]
Nudge

**Comment by chubin** [comment]
@kz6fittycent Sorry didn't do it et, but I didn't forget it. Thank you for pining me

**Pull request merged**
