### PR TITLE
Add Norwegian translation

### PR DESCRIPTION
**Pull request by stigok**

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much @stigok 
Can you please add Nynorsk too?

**Comment by stigok** [comment]
I'll see what I can do. I'll have to ask around ;)

**Comment by chubin** [comment]
@stigok Thank you very much! I think it should be quite easy to find some one who can help with it.
We can also ask @unhammer who helped with wttr.in translation, I think he could help; he speaks Nynorsk as far as I remember

**Comment by unhammer** [comment]
`nn` is identical in this case :-)

Btw, why the country variant (`_NO`) on the locale? There aren't really any non-Norway variants of Bokmål ;)

**Comment by stigok** [comment]
@unhammer are you adding an identical PR for `nn` or should I do it?
The reason for the trailing `_NO` i can't remember right now. But I *do* remember there was a reason for it :eyes:

**Comment by unhammer** [comment]
please add – I've never heard of pyphoon before this :)

**Comment by chubin** [comment]
@unhammer But you've heard about wttr.in, and wttr.in uses pyphoon:
try `curl wttr.in/Moon`

**Comment by NitroNils** [comment]
Hey, I'm up for some Norwegian translation now and then.Just don't know exactly how to get started!Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [chubin/pyphoon] Add Norwegian translation (#17)From: Igor Chubin To: chubin/pyphoon CC: Subscribed @unhammer But you've heard about wttr.in, and wttr.in uses pyphoon:
try curl wttr.in/Moon

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chubin/pyphoon","title":"chubin/pyphoon","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/chubin/pyphoon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chubin in #17: @unhammer But you've heard about wttr.in, and wttr.in uses pyphoon:\r\ntry `curl wttr.in/Moon`"}],"action":{"name":"View Pull Request","url":"https://github.com/chubin/pyphoon/pull/17#issuecomment-422821842"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chubin/pyphoon/pull/17#issuecomment-422821842",
"url": "https://github.com/chubin/pyphoon/pull/17#issuecomment-422821842",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [chubin/pyphoon] Add Norwegian translation (#17)",
"sections": [
{
"text": "",
"activityTitle": "**Igor Chubin**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@chubin",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"chubin/pyphoon\",\n\"issueId\": 17,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/chubin/pyphoon/pull/17#issuecomment-422821842"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355242162\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by chubin** [comment]
Thank you guys! @NitroNils @unhammer

**Pull request merged**
