### PR TITLE
South hemisphere reminder

### PR DESCRIPTION
**Pull request by martinbra**
Updates #1 , creating a reminder when south hemisphere is set using `-S`.
I created a mutually exclusive argument group with -S and -s, so that only one can be provided.
It changed the way to set the default value for the variable.

```
# pyphoon -S north -l en -n 6 2020-01-01
       -..
         .`.     New Moon +
         O ).    5 21:44:28
        ) ||.    First Quarter -
        ..'/     2  1:46:52
       -''

# pyphoon -S south -l en -n 6 2020-01-01
    ,,-
  /,``   New Moon +
 `|| (   5 21:44:28
 `( O    First Quarter -
  `.`    2  1:46:52
    ``-  (Southern Hemisphere)

# pyphoon -s south -l en -n 6 2020-01-01
    ,,-
  /,``   New Moon +
 `|| (   5 21:44:28
 `( O    First Quarter -
  `.`    2  1:46:52
    ``-

```

### CODE REVIEW

**Comment by martinbra** [comment]
https://github.com/chubin/wttr.in/issues/247 has some considerations from @iago-lito that should be addressed/answered before merging.

**Comment by martinbra** [comment]
Fixes #1 and #27 
I'm sorry for merging both in a single PR.

**Comment by martinbra** [comment]
Reverting back to draft to include @iago-lito comments in https://github.com/chubin/wttr.in/issues/247.

**Review by iago-lito — APPROVED** [review]

**Comment by chubin** [comment]
I think that after all fixes we should release the next (0.2) version, and ask @lucasrodes
to update the PyPI package. After that we can mention direct pip installation with `pip install pyphoon` in README.md

**Comment by lucasrodes** [comment]
Hi @chubin , 
If I understand you correctly, you'd like to have the name "pyphoon" available on PyPi, right? I can check whether this is possible on PyPi. On my side, it is fine, as the library is actually not being versioned (hence the repository should suffice).

**Comment by martinbra** [comment]
@lucasrodes , I think you already are the [maintainer there](https://pypi.org/project/pyphoon/), or is that another lucasrodes ?
Anyway, I think @chubin wants to finish all the hemisphere translations before publishing it there. Is that correct? We are still missing bg, ca, cs, da, et, el, es, fi, hr, ia, it, ja, nl, pl, ro, sk and sr.

**Comment by lucasrodes** [comment]
That's me, for another project I was working on (typhoon related). Flexible on giving the pypi domain to you!

**Comment by chubin** [comment]
@lucasrodes Lucas, feel free to contribute :-)

If you don't need the `pyphoon` package on pypi it would be very cool, if we could have it.

As we chosen the name for the project (pyphoon) 5 years ago
this word was not taken, and it was a good pun for `phoon` written in `P`ascal in 1979
that was reimplemented in Python now.

Fist time I saw this name on PyPI I even thought that someone packaged our pyphonn
and uploaded it. I didn't realize at first that it is completely unrelated project that
have the same name (because I remember how I checked if the name is not already used).

Of course it would be very good, if you could give the package name to us.
Thank you very much for it

**Comment by lucasrodes** [comment]
@chubin Sorry I did not answer before, please feel free to reach me out so I can transfer this to whoever is to be in charge!

Have a nice day :)!

**Comment by chubin** [comment]
@lucasrodes I've contacted you via email

**Pull request merged**
